export const ACTIONS = {
  ADD_PAGE: "ADD_PAGE",
  REMOVE_PAGE: "REMOVE_PAGE",
  EXPEND_PAGE: "EXPEND_PAGE",
  DRAG_AND_DROP: "DRAG_AND_DROP",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  CHANGE_PAGE_NAME: "CHANGE_PAGE_NAME",
  CHANGE_BLOCK_NAME: "CHANGE_BLOCK_NAME",
  REMOVE_BLOCK: "REMOVE_BLOCK",
  ADD_BLOCK: "ADD_BLOCK",
};

export const INITIAL_PAGE_NAME = "New Page";
export const INITIAL_PAGE_EXPENDED = true;
export const INITIAL_PAGE_PAGES = [];
export const INITIAL_PAGE_BLOCKS = ["New Block"];
